### ISSUE TITLE
[survey] System calls in a TCP connection

### ISSUE THREAD

**Issue by at15** [at15/bop-bpf#1]
## TODO

- [ ] what system calls are involved
- [ ] a simple tcp client and server in c(pp?) & go
- [ ] trace it using bcc

## Reference

- https://developer.ibm.com/technologies/systems/articles/au-tcpsystemcalls/
